# Autor: DannGzShot
# Fecha de creacion: 16/03/2026
# Descripcion: Define los puertos que escucha Apache para el gateway HTTPS local.

Listen 18080

<IfModule ssl_module>
    Listen 8001
</IfModule>

<IfModule mod_gnutls.c>
    Listen 8001
</IfModule>
